name: Check PR can be merged
on:
  pull_request:
    types: [labeled]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          reviewers-number: 2
          merge-method: "squash"
          auto-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}